### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by elaniquilador01**
Added tasks to food and storage quests missing them
Changed Ad Astra tasks from visiting dimensions to getting the advancements for doing so, possible Heracles bug

### CODE REVIEW

**Comment by SubordinalBlue** [comment]
Commit diffs look good.

I'm curious: the ad Astra dimension tasks that this removes... were they put in to the json "by hand" or were they mad using Heracles' in-game UI?

The from part looks weird, maybe?, "minecraft:". I'm likely wrong, but I would have guessed it's need a world, like "minecraft:overworld" (or just "overworld" with Herc. assuming the 'minecraft:' prefix.

**Comment by elaniquilador01** [comment]
I made them in game, it did say minecraft:overworld at first but I tried deleting that, maybe that's the issue, I thought someone trying to go from one planet to another wouldn't count and I wanted the quest to only detect that they arrived at the dimension wanted while ignoring where they cane from

**Comment by SubordinalBlue** [comment]
I'll commit this now.

If we can't get Herc to not care what dimension a player is leaving _from_, perhaps a composite quest covering all possible originating dimensions will work. That has to be edited into the json though. I'll see if I can find an example of how to write a composite task on/with my phone.

**Comment by elaniquilador01** [comment]
No need, the advancements basically do that, I should have checked that they existes while doing the quests

**Comment by SubordinalBlue** [comment]
Good solution.

Would like our collective understanding of Herc be complete _and_ help Herc be all it can be.

I really do think Herc and Hermes, and using all they can/will be able to do, could help set AoF packs apart.

**Pull request merged**
